[browser]
gatherUsageStats = false

[client]
toolbarMode = "minimal"

[theme]
base = "light"
primaryColor = "#00543f"
backgroundColor = "#f6f7f3"
secondaryBackgroundColor = "#ffffff"
textColor = "#0c231d"
